#!/bin/bash

sudo rm /usr/share/arete-lib.sh 2>/dev/null
sudo rm /usr/share/arete.sh 2>/dev/null
sudo unlink /usr/sbin/arete 2>/dev/null

sudo cp arete-lib.sh arete.sh /usr/lib
sudo ln -nf /usr/lib/arete.sh /usr/sbin/arete
